### ISSUE TITLE
Disable mutli prefix

### ISSUE THREAD

**Issue by a092devs** [TG-UBotX/TG-UBotX#1]
Please disable mutli prefix issue
I pr'ed for few modules here 3ec4382. Please fix this.

**Comment by HitaloKun** [comment]
I'll do it, thanks for the tip.

**Comment by HitaloKun** [comment]
@a092devs done, in case you find any commands that need this fix, let me know here.

**Comment by a092devs** [comment]
Ok will let you know by tomorrow.
